name: Node.JS CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Dependencies using NPM
      run: npm install
    - name: Run NPM test
      run: npm test
    - name: Run the build
      run: npm run build
      env:
        CI: true
 
